services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$SA_PASSWORD\" -C -No -Q 'SELECT 1' || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: HospitalManagement/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__HospitalDb: "Server=db;Database=HospitalManagement;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
    depends_on:
      db:
        condition: service_healthy

  auth:
    build:
      context: .
      dockerfile: HospitalManagement.Auth/Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__AuthDb: "Server=db;Database=HospitalManagementAuth;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
    depends_on:
      db:
        condition: service_healthy


volumes:
  sqldata:  