namespace: hms-dev

services:
  auth:
    image: hospitalmanagement-auth:v3
    port: 8080
    env:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__AuthDb: "Server=db;Database=HospitalManagementAuth;User Id=sa;Password=$(DB_PASSWORD);TrustServerCertificate=True"
    secretEnv:
      DB_PASSWORD: DB_PASSWORD
      Jwt__Key: JWT_KEY
      Jwt__Issuer: JWT_ISSUER
      Jwt__Audience: JWT_AUDIENCE
  appointments:
    image: hospitalmanagement-appointments:v4
    port: 8080
    env:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__AppointmentDb: "Server=db;Database=HospitalManagementAppointments;User Id=sa;Password=$(DB_PASSWORD);TrustServerCertificate=True"
      QueryService__BaseUrl: "http://queryservice:8080"
    secretEnv:
      DB_PASSWORD: DB_PASSWORD
      Jwt__Key: JWT_KEY
      Jwt__Issuer: JWT_ISSUER
      Jwt__Audience: JWT_AUDIENCE

  command:
    image: hospitalmanagement-command:v3
    port: 8080
    env:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__HospitalManagementCQRS: "Server=db;Database=HospitalManagementCQRS;User Id=sa;Password=$(DB_PASSWORD);TrustServerCertificate=True"
      Redis__ConnectionString: "redis:6379"
    secretEnv:
      DB_PASSWORD: DB_PASSWORD
      Jwt__Key: JWT_KEY
      Jwt__Issuer: JWT_ISSUER
      Jwt__Audience: JWT_AUDIENCE

  queryservice:
    image: hospitalmanagement-queryservice:v3
    port: 8080
    env:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__HospitalManagementCQRS: "Server=db;Database=HospitalManagementCQRS;User Id=sa;Password=$(DB_PASSWORD);TrustServerCertificate=True"
      Redis__ConnectionString: "redis:6379"
      AppointmentService__BaseUrl: "http://appointments:8080"
    secretEnv:
      DB_PASSWORD: DB_PASSWORD
      Jwt__Key: JWT_KEY
      Jwt__Issuer: JWT_ISSUER
      Jwt__Audience: JWT_AUDIENCE

  invoiceservice:
    image: hospitalmanagement-invoiceservice:v3
    port: 8080
    env:
      ASPNETCORE_ENVIRONMENT: "Development"
      AppointmentService__BaseUrl: "http://appointments:8080"
      Jwt__ExpiryMinutes: "60"
    secretEnv:
      Jwt__Key: JWT_KEY
      Jwt__Issuer: JWT_ISSUER
      Jwt__Audience: JWT_AUDIENCE
