apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: hms-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: hospitalmanagement-auth:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hms-secrets
                  key: DB_PASSWORD
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__AuthDb
              value: "Server=db;Database=HospitalManagementAuth;User Id=sa;Password=$(DB_PASSWORD);TrustServerCertificate=True"
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: hms-secrets
                  key: JWT_KEY
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: hms-secrets
                  key: JWT_ISSUER
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: hms-secrets
                  key: JWT_AUDIENCE
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: hms-dev
spec:
  selector:
    app: auth
  ports:
    - port: 8080
      targetPort: 8080
