apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceservice
  namespace: hms-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoiceservice
  template:
    metadata:
      labels:
        app: invoiceservice
    spec:
      containers:
        - name: invoiceservice
          image: hospitalmanagement-invoiceservice:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: hms-secrets
                  key: JWT_KEY
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: hms-secrets
                  key: JWT_ISSUER
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: hms-secrets
                  key: JWT_AUDIENCE
            - name: Jwt__ExpiryMinutes
              value: "60"
            - name: AppointmentService__BaseUrl
              value: "http://appointments:8080"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: invoiceservice
  namespace: hms-dev
spec:
  selector:
    app: invoiceservice
  ports:
    - port: 8080
      targetPort: 8080
